SYMPTOMS = [
    {"code": "G01", "name": "Deadline tugas sudah dekat", "status": "aktif"},
    {"code": "G02", "name": "Banyak tugas belum selesai", "status": "aktif"},
    {"code": "G03", "name": "Sulit memahami materi dasar", "status": "aktif"},
    {"code": "G04", "name": "Sering lupa konsep setelah belajar", "status": "aktif"},
    {"code": "G05", "name": "Sering bingung saat mengerjakan soal atau praktik", "status": "aktif"},
    {"code": "G06", "name": "Sulit fokus ketika belajar", "status": "aktif"},
    {"code": "G07", "name": "Sering terdistraksi gadget", "status": "aktif"},
    {"code": "G08", "name": "Waktu belajar tidak teratur", "status": "aktif"},
    {"code": "G09", "name": "Sering menunda tugas", "status": "aktif"},
    {"code": "G10", "name": "Kurang latihan soal atau praktik", "status": "aktif"},
    {"code": "G11", "name": "Tidak tahu bagian mana yang harus dipelajari dulu", "status": "aktif"},
    {"code": "G12", "name": "Nilai tugas atau kuis menurun", "status": "aktif"},
    {"code": "G13", "name": "Materi terasa terlalu sulit", "status": "aktif"},
    {"code": "G14", "name": "Kurang berdiskusi dengan teman", "status": "aktif"},
    {"code": "G15", "name": "Jarang bertanya kepada dosen atau asisten", "status": "aktif"},
    {"code": "G16", "name": "Lingkungan belajar kurang kondusif", "status": "aktif"},
    {"code": "G17", "name": "Waktu belajar sedikit", "status": "aktif"},
    {"code": "G18", "name": "Progres tugas masih rendah", "status": "aktif"},
    {"code": "G19", "name": "Tugas memiliki bobot nilai besar", "status": "aktif"},
    {"code": "G20", "name": "Mendekati ujian atau presentasi", "status": "aktif"},
]

RECOMMENDATIONS = [
    {
        "code": "O01",
        "name": "Prioritaskan tugas dengan deadline terdekat",
        "description": "Susun tugas berdasarkan tenggat waktu paling dekat.",
        "status": "aktif",
    },
    {
        "code": "O02",
        "name": "Fokus pada tugas dengan bobot nilai besar",
        "description": "Dahulukan tugas yang paling memengaruhi nilai akhir.",
        "status": "aktif",
    },
    {
        "code": "O03",
        "name": "Pecah tugas besar menjadi beberapa subtask kecil",
        "description": "Bagi pekerjaan besar agar lebih mudah dikerjakan.",
        "status": "aktif",
    },
    {
        "code": "O04",
        "name": "Buat jadwal belajar harian",
        "description": "Tetapkan waktu belajar rutin setiap hari.",
        "status": "aktif",
    },
    {
        "code": "O05",
        "name": "Gunakan metode Pomodoro atau belajar bertahap",
        "description": "Belajar dalam interval fokus dengan jeda istirahat.",
        "status": "aktif",
    },
    {
        "code": "O06",
        "name": "Pelajari ulang konsep dasar",
        "description": "Kuatkan pemahaman fondasi sebelum materi lanjutan.",
        "status": "aktif",
    },
    {
        "code": "O07",
        "name": "Perbanyak latihan soal atau praktik",
        "description": "Tingkatkan penguasaan melalui latihan rutin.",
        "status": "aktif",
    },
    {
        "code": "O08",
        "name": "Kurangi distraksi gadget saat belajar",
        "description": "Matikan notifikasi dan jauhkan gangguan.",
        "status": "aktif",
    },
    {
        "code": "O09",
        "name": "Cari tempat belajar yang lebih kondusif",
        "description": "Pilih lingkungan tenang dan nyaman untuk belajar.",
        "status": "aktif",
    },
    {
        "code": "O10",
        "name": "Diskusi dengan teman atau kelompok belajar",
        "description": "Belajar bersama untuk saling melengkapi pemahaman.",
        "status": "aktif",
    },
    {
        "code": "O11",
        "name": "Konsultasi dengan dosen atau asisten",
        "description": "Tanyakan materi sulit langsung ke pengajar.",
        "status": "aktif",
    },
    {
        "code": "O12",
        "name": "Review materi menjelang ujian atau presentasi",
        "description": "Ulang materi penting sebelum penilaian.",
        "status": "aktif",
    },
    {
        "code": "O13",
        "name": "Cari referensi tambahan (modul, video, dokumentasi)",
        "description": "Perkaya sumber belajar dari berbagai media.",
        "status": "aktif",
    },
    {
        "code": "O14",
        "name": "Buat daftar prioritas belajar berdasarkan urgensi",
        "description": "Urutkan materi/tugas sesuai tingkat kepentingan.",
        "status": "aktif",
    },
    {
        "code": "O15",
        "name": "Evaluasi ulang pola belajar yang sedang digunakan",
        "description": "Tinjau dan perbaiki kebiasaan belajar saat ini.",
        "status": "aktif",
    },
]

RULES = [
    {"code": "R01", "symptom_codes": ["G01", "G18"], "recommendation_code": "O01", "cf_pakar": 0.90, "status": "aktif"},
    {"code": "R02", "symptom_codes": ["G19", "G02"], "recommendation_code": "O02", "cf_pakar": 0.85, "status": "aktif"},
    {"code": "R03", "symptom_codes": ["G09", "G18"], "recommendation_code": "O03", "cf_pakar": 0.80, "status": "aktif"},
    {"code": "R04", "symptom_codes": ["G02", "G08", "G09"], "recommendation_code": "O04", "cf_pakar": 0.90, "status": "aktif"},
    {"code": "R05", "symptom_codes": ["G06", "G17"], "recommendation_code": "O05", "cf_pakar": 0.75, "status": "aktif"},
    {"code": "R06", "symptom_codes": ["G03", "G13"], "recommendation_code": "O06", "cf_pakar": 0.85, "status": "aktif"},
    {"code": "R07", "symptom_codes": ["G05", "G10"], "recommendation_code": "O07", "cf_pakar": 0.80, "status": "aktif"},
    {"code": "R08", "symptom_codes": ["G06", "G07"], "recommendation_code": "O08", "cf_pakar": 0.85, "status": "aktif"},
    {"code": "R09", "symptom_codes": ["G16"], "recommendation_code": "O09", "cf_pakar": 0.70, "status": "aktif"},
    {"code": "R10", "symptom_codes": ["G14"], "recommendation_code": "O10", "cf_pakar": 0.70, "status": "aktif"},
    {"code": "R11", "symptom_codes": ["G15", "G13"], "recommendation_code": "O11", "cf_pakar": 0.75, "status": "aktif"},
    {"code": "R12", "symptom_codes": ["G20", "G12"], "recommendation_code": "O12", "cf_pakar": 0.85, "status": "aktif"},
    {"code": "R13", "symptom_codes": ["G03", "G04"], "recommendation_code": "O13", "cf_pakar": 0.70, "status": "aktif"},
    {"code": "R14", "symptom_codes": ["G11"], "recommendation_code": "O14", "cf_pakar": 0.80, "status": "aktif"},
    {"code": "R15", "symptom_codes": ["G12", "G04"], "recommendation_code": "O15", "cf_pakar": 0.70, "status": "aktif"},
]

SEED_USERS = [
    {
        "id": "admin-seed",
        "nama": "Admin StudyWise",
        "email": "admin@studywise.ac.id",
        "role": "admin",
        "nim": None,
        "program_studi": None,
        "semester": None,
        "jenis_kelamin": None,
        "status": "aktif",
    },
    {
        "id": "mahasiswa-seed",
        "nama": "Andi Pratama",
        "email": "mahasiswa@studywise.ac.id",
        "role": "mahasiswa",
        "nim": "2231140012",
        "program_studi": "D4 - Teknologi Rekayasa Perangkat Lunak",
        "semester": 4,
        "jenis_kelamin": "laki-laki",
        "status": "aktif",
    },
]

SEED_PASSWORD = "studywise123"
